#docker run --net=host -it -e NGROK_AUTHTOKEN=xyz ngrok/ngrok:latest http 80

name: Ngrok
services:
  ngrock:
    image: ngrok/ngrok:latest
    tty: true
    stdin_open: true
    environment:
      - NGROK_AUTHTOKEN=358pRJuvxF9SMXRLsmzh4LxxIhl_3T824QayFUfd62PgEuVnc
    command: http 80
    ports:
      - "80:80"

  gulp:
    build:
      context: .
      dockerfile: Dockerfile-gulp
    tty: true
    stdin_open: true
    volumes:
      - ./prova:/app
