name: PracticaVite
services:
  node-diw:
    image: node:22.12
    tty: true
    stdin_open: true
    working_dir: /appdiw
    volumes:
      - ./vite:/appdiw
    ports:
      - "8082:5173"

  web:
    image: httpd
    tty: true
    stdin_open: true
    working_dir: /usr/local/apache2/htdocs/
    volumes:
      - ./vite:/usr/local/apache2/htdocs/
    ports:
      - "84:80"

  scss:
    build:
      context: .
      dockerfile: Dockerfile-scss
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./vite/marc-vite/src/:/app
